/**
 * Image uploads via Cloudinary.
 *
 * The previous system wrote uploads to local disk and served them from
 * `/uploads`. That breaks in three ways the moment it leaves one developer's
 * machine:
 *
 *   • **Multiple instances.** An image uploaded to instance A is a 404 on
 *     instance B, so photos appear and disappear depending on which server
 *     answered.
 *   • **Ephemeral filesystems.** Render and Railway containers are replaced on
 *     every deploy, taking every uploaded file with them.
 *   • **No CDN, no transforms.** A 6MB phone photo was served at full size to
 *     a 64px avatar slot.
 *
 * Files are streamed straight from memory to Cloudinary and never touch the
 * disk. Only the resulting URL and `publicId` are stored — the id matters,
 * because without it an orphaned image can never be deleted.
 */

import { v2 as cloudinary, type UploadApiResponse } from 'cloudinary';
import { ERROR_CODES, LIMITS, type MediaAsset } from '@pawsitive/shared';
import { env, isCloudinaryConfigured } from '../config/env.js';
import { createLogger } from '../config/logger.js';
import { ApiError } from '../utils/api-error.js';

const log = createLogger('uploads');

let configured = false;

function configure(): void {
  if (configured || !isCloudinaryConfigured) return;

  cloudinary.config({
    cloud_name: env.CLOUDINARY_CLOUD_NAME,
    api_key: env.CLOUDINARY_API_KEY,
    api_secret: env.CLOUDINARY_API_SECRET,
    secure: true,
  });

  configured = true;
}

export type UploadFolder = 'pets' | 'avatars' | 'clinics' | 'records';

export interface UploadOptions {
  folder: UploadFolder;
  /** Stable id so re-uploading replaces rather than accumulating copies. */
  publicId?: string;
}

/**
 * Upload a buffer and return the stored asset.
 *
 * Transformations are applied **on upload**, not on delivery: a phone camera
 * produces 4000px images and nothing in this product displays one larger than
 * about 1200px. Capping at upload means we are not paying to store or transform
 * pixels nobody will ever see.
 */
export async function uploadImage(
  buffer: Buffer,
  mimetype: string,
  options: UploadOptions,
): Promise<MediaAsset> {
  if (!isCloudinaryConfigured) {
    throw new ApiError({
      statusCode: 503,
      code: ERROR_CODES.UPLOAD_FAILED,
      message: 'Image uploads are not configured on this server.',
    });
  }

  assertAllowedImage(mimetype, buffer.byteLength);
  configure();

  try {
    const result = await new Promise<UploadApiResponse>((resolve, reject) => {
      const stream = cloudinary.uploader.upload_stream(
        {
          folder: `${env.CLOUDINARY_FOLDER}/${options.folder}`,
          ...(options.publicId ? { public_id: options.publicId, overwrite: true } : {}),
          resource_type: 'image',
          /* Strip EXIF. A phone photo carries GPS coordinates, which for a pet
             picture means publishing the owner's home address. */
          transformation: [
            { width: 1200, height: 1200, crop: 'limit' },
            { quality: 'auto:good', fetch_format: 'auto' },
          ],
          /* `false` keeps the original's metadata out of the stored asset. */
          image_metadata: false,
          invalidate: true,
        },
        (error, uploaded) => {
          if (error || !uploaded) {
            reject(error ?? new Error('Cloudinary returned no result'));
            return;
          }
          resolve(uploaded);
        },
      );

      stream.end(buffer);
    });

    return {
      url: result.secure_url,
      publicId: result.public_id,
      /* A small, blurred derivative for blur-up loading — generated by URL
         transform rather than a second upload. */
      thumbnailUrl: cloudinary.url(result.public_id, {
        secure: true,
        transformation: [
          { width: 64, height: 64, crop: 'fill', gravity: 'auto' },
          { quality: 'auto:low', fetch_format: 'auto' },
        ],
      }),
      width: result.width,
      height: result.height,
      format: result.format,
      bytes: result.bytes,
      uploadedAt: new Date().toISOString(),
    };
  } catch (error) {
    log.error({ err: error, folder: options.folder }, 'Cloudinary upload failed');

    throw new ApiError({
      statusCode: 502,
      code: ERROR_CODES.UPLOAD_FAILED,
      cause: error,
    });
  }
}

/**
 * Delete a stored asset.
 *
 * Called when a photo is replaced or a pet is archived. Failures are logged
 * rather than thrown: an orphaned image is a storage cost, whereas failing the
 * user's request because cleanup did not work is a broken feature.
 */
export async function deleteImage(publicId: string): Promise<boolean> {
  if (!isCloudinaryConfigured || !publicId) return false;

  configure();

  try {
    const result = await cloudinary.uploader.destroy(publicId, { invalidate: true });
    return result.result === 'ok';
  } catch (error) {
    log.error({ err: error, publicId }, 'Failed to delete a Cloudinary asset');
    return false;
  }
}

/**
 * Validate the declared type against the file's actual magic bytes.
 *
 * A client-supplied `Content-Type` is a hint, not a fact — `image/png` on an
 * HTML payload is the classic stored-XSS route, and on an SVG it is an active
 * one. Checking the signature means the bytes have to actually be an image.
 */
function assertAllowedImage(mimetype: string, byteLength: number): void {
  if (byteLength > LIMITS.MAX_UPLOAD_BYTES) {
    throw new ApiError({
      statusCode: 413,
      code: ERROR_CODES.FILE_TOO_LARGE,
      message: `Images must be under ${Math.round(LIMITS.MAX_UPLOAD_BYTES / 1024 / 1024)}MB.`,
    });
  }

  if (!(LIMITS.ALLOWED_IMAGE_TYPES as readonly string[]).includes(mimetype)) {
    throw new ApiError({
      statusCode: 400,
      code: ERROR_CODES.UNSUPPORTED_FILE_TYPE,
      message: 'Please upload a JPEG, PNG, WebP or AVIF image.',
    });
  }
}

/** Magic-byte signatures for the formats we accept. */
const SIGNATURES: { mime: string; test: (buffer: Buffer) => boolean }[] = [
  { mime: 'image/jpeg', test: (b) => b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff },
  {
    mime: 'image/png',
    test: (b) => b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47,
  },
  {
    mime: 'image/webp',
    test: (b) => b.subarray(0, 4).toString('ascii') === 'RIFF' && b.subarray(8, 12).toString('ascii') === 'WEBP',
  },
  {
    /* AVIF and other ISO-BMFF images declare their brand in the `ftyp` box. */
    mime: 'image/avif',
    test: (b) => b.subarray(4, 8).toString('ascii') === 'ftyp',
  },
];

export function assertRealImage(buffer: Buffer, declaredMime: string): void {
  if (buffer.byteLength < 12) {
    throw new ApiError({
      statusCode: 400,
      code: ERROR_CODES.UNSUPPORTED_FILE_TYPE,
      message: 'That file does not look like an image.',
    });
  }

  const match = SIGNATURES.find((signature) => signature.test(buffer));

  if (!match || match.mime !== declaredMime) {
    throw new ApiError({
      statusCode: 400,
      code: ERROR_CODES.UNSUPPORTED_FILE_TYPE,
      message: 'That file is not a valid image, or its type does not match its contents.',
      context: { declaredMime, detected: match?.mime ?? 'unknown' },
    });
  }
}
